#! /bin/bash
#
mpif90 -f90=ifort -c invar.f90
mpif90 -f90=ifort -c solvar.f90
mpif90 -f90=ifort -c totvar.f90
mpif90 -f90=ifort -c timevar.f90
mpif90 -f90=ifort -c main.f90
mpif90 -f90=ifort -c version.f90
mpif90 -f90=ifort -c input.f90
mpif90 -f90=ifort -c angle.f90
mpif90 -f90=ifort -c readmt.f90
mpif90 -f90=ifort -c readxs.f90
mpif90 -f90=ifort -c readsrc.f90
mpif90 -f90=ifort -c readbc.f90
mpif90 -f90=ifort -c check.f90
mpif90 -f90=ifort -c echo.f90
mpif90 -f90=ifort -c psds.f90
mpif90 -f90=ifort -c bnc.f90
mpif90 -f90=ifort -c solve.f90
mpif90 -f90=ifort -c idomats.f90
mpif90 -f90=ifort -c legpoly.f90
mpif90 -f90=ifort -c inner.f90
mpif90 -f90=ifort -c sweep.f90
mpif90 -f90=ifort -c idot.f90
mpif90 -f90=ifort -c matsweep.f90
mpif90 -f90=ifort -c gammas.f90
mpif90 -f90=ifort -c jima.f90
mpif90 -f90=ifort -c afcm.f90
mpif90 -f90=ifort -c conk.f90
mpif90 -f90=ifort -c cgsolve.f90
mpif90 -f90=ifort -c pbj.f90
mpif90 -f90=ifort -c gthr.f90
mpif90 -f90=ifort -c output.f90
mpif90 -f90=ifort -lblas -llapack -o pidosits *.o
#
