#! /bin/bash
#
mpif90 -f90=ifort -traceback -check bounds -c invar.f90
mpif90 -f90=ifort -traceback -check bounds -c solvar.f90
mpif90 -f90=ifort -traceback -check bounds -c totvar.f90
mpif90 -f90=ifort -traceback -check bounds -c timevar.f90
mpif90 -f90=ifort -traceback -check bounds -c main.f90
mpif90 -f90=ifort -traceback -check bounds -c version.f90
mpif90 -f90=ifort -traceback -check bounds -c input.f90
mpif90 -f90=ifort -traceback -check bounds -c angle.f90
mpif90 -f90=ifort -traceback -check bounds -c readmt.f90
mpif90 -f90=ifort -traceback -check bounds -c readxs.f90
mpif90 -f90=ifort -traceback -check bounds -c readsrc.f90
mpif90 -f90=ifort -traceback -check bounds -c readbc.f90
mpif90 -f90=ifort -traceback -check bounds -c check.f90
mpif90 -f90=ifort -traceback -check bounds -c echo.f90
mpif90 -f90=ifort -traceback -check bounds -c psds.f90
mpif90 -f90=ifort -traceback -check bounds -c bnc.f90
mpif90 -f90=ifort -traceback -check bounds -c solve.f90
mpif90 -f90=ifort -traceback -check bounds -c idomats.f90
mpif90 -f90=ifort -traceback -check bounds -c legpoly.f90
mpif90 -f90=ifort -traceback -check bounds -c inner.f90
mpif90 -f90=ifort -traceback -check bounds -c sweep.f90
mpif90 -f90=ifort -traceback -check bounds -c idot.f90
mpif90 -f90=ifort -traceback -check bounds -c matsweep.f90
mpif90 -f90=ifort -traceback -check bounds -c gammas.f90
mpif90 -f90=ifort -traceback -check bounds -c jima.f90
mpif90 -f90=ifort -traceback -check bounds -c afcm.f90
mpif90 -f90=ifort -traceback -check bounds -c conk.f90
mpif90 -f90=ifort -traceback -check bounds -c cgsolve.f90
mpif90 -f90=ifort -traceback -check bounds -c pbj.f90
mpif90 -f90=ifort -traceback -check bounds -c gthr.f90
mpif90 -f90=ifort -traceback -check bounds -c output.f90
mpif90 -f90=ifort -traceback -check bounds -lblas -llapack -o debug_pidosits *.o
#
