#! /bin/bash
#
mpif90 -f90=ifort -traceback -check bounds -c invar.f90
mpif90 -f90=ifort -traceback -check bounds -c solvar.f90
mpif90 -f90=ifort -traceback -check bounds -c totvar.f90
mpif90 -f90=ifort -traceback -check bounds -c timevar.f90
mpif90 -f90=ifort -traceback -check bounds -c main.f90
mpif90 -f90=ifort -traceback -check bounds -c version.f90
mpif90 -f90=ifort -traceback -check bounds -c input.f90
mpif90 -f90=ifort -traceback -check bounds -c angle.f90
mpif90 -f90=ifort -traceback -check bounds -c readmt.f90
mpif90 -f90=ifort -traceback -check bounds -c readxs.f90
mpif90 -f90=ifort -traceback -check bounds -c readsrc.f90
mpif90 -f90=ifort -traceback -check bounds -c readbc.f90
mpif90 -f90=ifort -traceback -check bounds -c check.f90
mpif90 -f90=ifort -traceback -check bounds -c echo.f90
mpif90 -f90=ifort -traceback -check bounds -c psds.f90
mpif90 -f90=ifort -traceback -check bounds -c procgrid.f90
mpif90 -f90=ifort -traceback -check bounds -c bnc.f90
mpif90 -f90=ifort -traceback -check bounds -c solve.f90
mpif90 -f90=ifort -traceback -check bounds -c idomats.f90
mpif90 -f90=ifort -traceback -check bounds -c matsweep.f90
mpif90 -f90=ifort -traceback -check bounds -c gammas.f90
mpif90 -f90=ifort -traceback -check bounds -c jima.f90
mpif90 -f90=ifort -traceback -check bounds -c afcm.f90
mpif90 -f90=ifort -traceback -check bounds -c conk.f90
mpif90 -f90=ifort -traceback -check bounds -c gmrescgs.f90
mpif90 -f90=ifort -traceback -check bounds -c gmresmgs.f90
mpif90 -f90=ifort -traceback -check bounds -c gridcomm.f90
mpif90 -f90=ifort -traceback -check bounds -c avmult.f90
mpif90 -f90=ifort -traceback -check bounds -c precond.f90
mpif90 -f90=ifort -traceback -check bounds -c rotmat.f90
mpif90 -f90=ifort -traceback -check bounds -c idogthr.f90
mpif90 -f90=ifort -traceback -check bounds -c output.f90
mpif90 -f90=ifort -traceback -check bounds -lblas -llapack -o debug_pidosits *.o
#
