#!/bin/bash
mpiexec -s all -n 1 ../pidosits in1 $1o1
#mpiexec -s all -n 1 ../../dd-3d/pidosits rin1 ro1
#
mpiexec -s all -n 2 ../pidosits in2 $1o2
#mpiexec -s all -n 2 ../../dd-3d/pidosits rin2 ro2
#
mpiexec -s all -n 4 ../pidosits in4 $1o4
#mpiexec -s all -n 4 ../../dd-3d/pidosits rin4 ro4
#
mpiexec -s all -n 8 ../pidosits in8 $1o8
#mpiexec -s all -n 8 ../../dd-3d/pidosits rin8 ro8
#
mpiexec -s all -n 16 ../pidosits in16 $1o16
#mpiexec -s all -n 16 ../../dd-3d/pidosits rin16 ro16
#
mpiexec -s all -n 32 ../pidosits in32 $1o32
#mpiexec -s all -n 32 ../../dd-3d/pidosits rin32 ro32
#
mpiexec -s all -n 64 ../pidosits in64 $1o64
#mpiexec -s all -n 64 ../../dd-3d/pidosits rin64 ro64
#
mpiexec -s all -n 128 ../pidosits in128 $1o128
#mpiexec -s all -n 128 ../../dd-3d/pidosits rin128 ro128
#
